package com.yt.datastructure.datastructure.db.mybatis.domain;

import java.io.Serializable;
import java.util.Date;

public class OrderDO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.buyer_name
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    private String buyerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.cost
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    private Integer cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ware_name
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    private String wareName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.update_time
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_id
     *
     * @return the value of order.order_id
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_id
     *
     * @param orderId the value for order.order_id
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.buyer_name
     *
     * @return the value of order.buyer_name
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    public String getBuyerName() {
        return buyerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.buyer_name
     *
     * @param buyerName the value for order.buyer_name
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    public void setBuyerName(String buyerName) {
        this.buyerName = buyerName == null ? null : buyerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.cost
     *
     * @return the value of order.cost
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    public Integer getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.cost
     *
     * @param cost the value for order.cost
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    public void setCost(Integer cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ware_name
     *
     * @return the value of order.ware_name
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    public String getWareName() {
        return wareName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ware_name
     *
     * @param wareName the value for order.ware_name
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    public void setWareName(String wareName) {
        this.wareName = wareName == null ? null : wareName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @return the value of order.create_time
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_time
     *
     * @param createTime the value for order.create_time
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.update_time
     *
     * @return the value of order.update_time
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.update_time
     *
     * @param updateTime the value for order.update_time
     *
     * @mbggenerated Sat Nov 24 15:50:11 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}